### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by Hiram-Wong** [nktnet1/sync-request-curl#171] opened 2024-11-12 08:01 UTC
**Describe the bug**
install error

**To Reproduce**
yarn install sync-request-curl

**Screenshots**
```bash
CXX(target) Release/obj.target/node_libcurl/src/node_libcurl.o
clang++: warning: /Users/HiramWong/opt/anaconda3/include: 'linker' input unused [-Wunused-command-line-argument]
In file included from ../src/node_libcurl.cc:7:
In file included from ../src/Curl.h:13:
../node_modules/nan/nan.h:2621:8: error: no matching member function for call to 'SetAccessor'
 2621 |   tpl->SetAccessor(
      |   ~~~~~^~~~~~~~~~~
/Users/HiramWong/.electron-gyp/28.3.3/include/node/v8-template.h:816:8: note: candidate function not viable: no known conversion from 'v8::PropertyAttribute' to 'AccessControl' for 5th argument
  816 |   void SetAccessor(
      |        ^
  817 |       Local<Name> name, AccessorNameGetterCallback getter,
  818 |       AccessorNameSetterCallback setter = nullptr,
  819 |       Local<Value> data = Local<Value>(), AccessControl settings = DEFAULT,
      |                                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/HiramWong/.electron-gyp/28.3.3/include/node/v8-template.h:809:8: note: candidate function not viable: no known conversion from 'imp::NativeGetter' (aka 'void (*)(v8::Local<v8::Name>, const v8::PropertyCallbackInfo<v8::Value> &)') to 'AccessorGetterCallback' (aka 'void (*)(Local<String>, const PropertyCallbackInfo<Value> &)') for 2nd argument
  809 |   void SetAccessor(
      |        ^
  810 |       Local<String> name, AccessorGetterCallback getter,
      |                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ../src/node_libcurl.cc:7:
In file included from ../src/Curl.h:13:
../node_modules/nan/nan.h:2673:8: error: no matching member function for call to 'SetAccessor'
 2673 |   tpl->SetAccessor(
      |   ~~~~~^~~~~~~~~~~
/Users/HiramWong/.electron-gyp/28.3.3/include/node/v8-template.h:816:8: note: candidate function not viable: no known conversion from 'v8::PropertyAttribute' to 'AccessControl' for 5th argument
  816 |   void SetAccessor(
      |        ^
  817 |       Local<Name> name, AccessorNameGetterCallback getter,
  818 |       AccessorNameSetterCallback setter = nullptr,
  819 |       Local<Value> data = Local<Value>(), AccessControl settings = DEFAULT,
      |                                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/HiramWong/.electron-gyp/28.3.3/include/node/v8-template.h:809:8: note: candidate function not viable: no known conversion from 'imp::NativeGetter' (aka 'void (*)(v8::Local<v8::Name>, const v8::PropertyCallbackInfo<v8::Value> &)') to 'AccessorGetterCallback' (aka 'void (*)(Local<String>, const PropertyCallbackInfo<Value> &)') for 2nd argument
  809 |   void SetAccessor(
      |        ^
  810 |       Local<String> name, AccessorGetterCallback getter,
      |                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2 errors generated.
make: *** [Release/obj.target/node_libcurl/src/node_libcurl.o] Error 1
Error: `make` failed with exit code: 2
    at ChildProcess.onExit (/Users/HiramWong/Data/code/ZyPlayer/node_modules/@electron/rebuild/node_modules/node-gyp/lib/build.js:203:23)
    at ChildProcess.emit (node:events:519:28)
    at ChildProcess._handle.onexit (node:internal/child_process:294:12)
```

**Desktop (please complete the following information):**
 - macos15.1
 - nodejs 20.17.0
 - electron 28.2.0

**Comment by nktnet1** [comment] 2024-11-12 08:58
Installing `sync-request-curl` as a standalone on Macos v15.0.1, node 20.17.0, yarn 1.22.22 is working okay for me:

[sample.webm](https://github.com/user-attachments/assets/64060881-5a53-42fe-bc74-01c7ca4d5857)

since it's directly downloading the binary from node-libcurl. It appears that you're defaulting to building from source though (i.e. no binaries were found), so you may want to take a look at this section (and follow those links) in the documentation:
- https://github.com/nktnet1/sync-request-curl?tab=readme-ov-file#42-macos

I also suggest trying install node-libcurl - note that their docs says that, for newer macos version, building from source requires adding the env `npm_config_curl_include_dirs="$(xcrun --show-sdk-path)/usr/include"`, e.g.
```sh
npm_config_build_from_source=true npm_config_curl_include_dirs="$(xcrun --show-sdk-path)/usr/include" yarn add node-libcurl
```

If you're also unable to install node-libcurl, I suggest opening an issue there instead.

**Comment by Hiram-Wong** [comment] 2024-11-12 09:04
node-libcurl install success，but sync-request-curl error

**Comment by Hiram-Wong** [comment] 2024-11-22 14:58
i try this `yarn add sync-request-curl@latest` in  node version 20.17.0
```bash
└─ sync-request-curl@3.0.0
$ electron-builder install-app-deps
  • electron-builder  version=25.1.8
  • loaded configuration  file=/Users/HiramWong/Data/code/ZyPlayer/electron-builder.yml
  • executing @electron/rebuild  electronVersion=27.3.11 arch=arm64 buildFromSource=false appDir=./
  • installing native dependencies  arch=arm64
  • preparing       moduleName=easy-libcurl arch=arm64
  ⨯ Traceback (most recent call last):
  File "/Users/HiramWong/Data/code/ZyPlayer/node_modules/@electron/rebuild/node_modules/node-gyp/gyp/gyp_main.py", line 42, in <module>
    import gyp  # noqa: E402
    ^^^^^^^^^^
  File "/Users/HiramWong/Data/code/ZyPlayer/node_modules/@electron/rebuild/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 9, in <module>
    import gyp.input
  File "/Users/HiramWong/Data/code/ZyPlayer/node_modules/@electron/rebuild/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 19, in <module>
    from distutils.version import StrictVersion
ModuleNotFoundError: No module named 'distutils'
Error: `gyp` failed with exit code: 1
    at ChildProcess.onCpExit (/Users/HiramWong/Data/code/ZyPlayer/node_modules/@electron/rebuild/node_modules/node-gyp/lib/configure.js:325:16)
    at ChildProcess.emit (node:events:519:28)
    at ChildProcess._handle.onexit (node:internal/child_process:294:12)


  ⨯ node-gyp failed to rebuild '/Users/HiramWong/Data/code/ZyPlayer/node_modules/easy-libcurl'  failedTask=installAppDeps stackTrace=Error: node-gyp failed to rebuild '/Users/HiramWong/Data/code/ZyPlayer/node_modules/easy-libcurl'
    at ChildProcess.<anonymous> (/Users/HiramWong/Data/code/ZyPlayer/node_modules/@electron/rebuild/lib/module-type/node-gyp/node-gyp.js:121:24)
    at ChildProcess.emit (node:events:519:28)
    at ChildProcess._handle.onexit (node:internal/child_process:294:12)
error Command failed with exit code 1.
```

**Comment by nktnet1** [comment] 2024-11-23 02:27
hmm looks like it's still building from source.

Can you try creating a minimal reproducible repository? I don't have a way of reproducing this currenrly.

**Comment by Hiram-Wong** [comment] 2024-11-24 06:50
Still fail

```js
$ electron-builder install-app-deps
  • electron-builder  version=25.1.8
  • loaded configuration  file=/Users/HiramWong/Data/code/ZyPlayer/electron-builder.yml
  • executing @electron/rebuild  electronVersion=33.2.0 arch=arm64 buildFromSource=false appDir=./
  • installing native dependencies  arch=arm64
  • preparing       moduleName=node-libcurl arch=arm64
  ⨯ Traceback (most recent call last):
  File "/Users/HiramWong/Data/code/ZyPlayer/node_modules/@electron/rebuild/node_modules/node-gyp/gyp/gyp_main.py", line 42, in <module>
    import gyp  # noqa: E402
    ^^^^^^^^^^
  File "/Users/HiramWong/Data/code/ZyPlayer/node_modules/@electron/rebuild/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 9, in <module>
    import gyp.input
  File "/Users/HiramWong/Data/code/ZyPlayer/node_modules/@electron/rebuild/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 19, in <module>
    from distutils.version import StrictVersion
ModuleNotFoundError: No module named 'distutils'
Error: `gyp` failed with exit code: 1
    at ChildProcess.onCpExit (/Users/HiramWong/Data/code/ZyPlayer/node_modules/@electron/rebuild/node_modules/node-gyp/lib/configure.js:325:16)
    at ChildProcess.emit (node:events:519:28)
    at ChildProcess._handle.onexit (node:internal/child_process:294:12)


  ⨯ node-gyp failed to rebuild '/Users/HiramWong/Data/code/ZyPlayer/node_modules/node-libcurl'  failedTask=installAppDeps stackTrace=Error: node-gyp failed to rebuild '/Users/HiramWong/Data/code/ZyPlayer/node_modules/node-libcurl'
    at ChildProcess.<anonymous> (/Users/HiramWong/Data/code/ZyPlayer/node_modules/@electron/rebuild/lib/module-type/node-gyp/node-gyp.js:121:24)
    at ChildProcess.emit (node:events:519:28)
    at ChildProcess._handle.onexit (node:internal/child_process:294:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

**Comment by Hiram-Wong** [comment] 2024-11-24 07:17
use `npm_config_build_from_source=true npm_config_curl_include_dirs="$(xcrun --show-sdk-path)/usr/include" yarn add sync-request-curl@latest` is ok

**Comment by Hiram-Wong** [comment] 2024-11-24 07:24
for this eg , It seems that the performance has not improved.

```js
import syncFetch from 'sync-fetch';
import syncRequest from 'sync-request';
import syncRequestCurl from 'sync-request-curl';

let url = 'https://api.juejin.cn/interact_api/v1/pin_tab_lead?aid=2608&uuid=&spider=0?' + Math.random();

let t1 = new Date().getTime();
syncRequest('GET', url);
let t2 = new Date().getTime();
syncFetch(url, {});
let t3 = new Date().getTime();
syncRequestCurl('GET', url);
let t4 = new Date().getTime();

console.warn('syncRequest time-consuming:' + (t2 - t1) + 'ms');
console.warn('syncFetch time-consuming:' + (t3 - t2) + 'ms');
console.warn('syncRequestCurl time-consuming:' + (t4 - t3) + 'ms');
```

in linux 
syncRequest time-consuming:5338ms
syncFetch time-consuming:5683ms
syncRequestCurl time-consuming:5317ms

in mac
syncRequest time-consuming:228ms
syncFetch time-consuming:364ms
syncRequestCurl time-consuming:246ms



I have another question if I use it in the main thread, will it block the main thread?

**Comment by nktnet1** [comment] 2024-11-24 08:09
Hi Hiram,

It's really odd that your linux times are that high. For example, this is what I get running your code:
```
$ npx tsx index.ts
syncRequest time-consuming:1085ms
syncFetch time-consuming:349ms
syncRequestCurl time-consuming:323ms
```

Often times, the bottleneck is the server, not the HTTP client.

Regardless, I suggest running these tests more than just once - for example, 100+ times for each method. There was something similar done [here](https://github.com/MiguelGuthridge/best-test-request).

---

> I have another question if I use it in the main thread, will it block the main thread?

Yes.

---

In general, I would always recommend an async alternative if possible. Please see the caveat section of sync-request-curl.

I'll close this issue though, given that the installation issues have been sorted out.

**Closed by nktnet1** 2024-11-24 08:09 UTC
